version: "3.4"

services:

  posa1:
    image: "webcgi/coin:openposa"
    tty: true
    ports:
      - 8647:8647
      - 30315:30315
      - 10646:10646
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8545
      PORT: 30315
      RUST_BACKTRACE: 1
    volumes:
      - ./config1.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys1/ethereum:/openethereum/keys
    container_name: posa1
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  posa2:
    image: "webcgi/coin:openposa"
    tty: true
    ports:
      - 30316:30316
    depends_on:
      - posa1
    environment:
      ENV: ETHERNODE2
      RPCPORT: 8545
      PORT: 30316
      RUST_BACKTRACE: 1
    volumes:
      - ./config2.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys2/ethereum:/openethereum/keys
    container_name: posa2
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  posa3:
    image: "webcgi/coin:openposa"
    tty: true
    depends_on:
      - posa2
    ports:
      - 30317:30317
    environment:
      ENV: ETHERNODE3
      RPCPORT: 8545
      PORT: 30317
      RUST_BACKTRACE: 1
    volumes:
      - ./config3.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys3/ethereum:/openethereum/keys
    container_name: posa3
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  posa4:
    image: "webcgi/coin:openposa"
    tty: true
    depends_on:
      - posa2
    ports:
      - 30318:30318
    environment:
      ENV: ETHERNODE4
      RPCPORT: 8545
      PORT: 30318
      RUST_BACKTRACE: 1
    volumes:
      - ./config4.toml:/openethereum/config.toml
      - ./genesis1.json:/openethereum/genesis.json
      - ./password:/openethereum/password
      - ./nodes:/openethereum/nodes
      - ./keys4/ethereum:/openethereum/keys
    container_name: posa4
    command: >
      sh -c "cd ~/
            /openethereum/target/release/openethereum --config /openethereum/config.toml"
    working_dir: /openethereum

  scan:
    image: "nara7875/acentscan:17"
    ports:
      - 3013:3000
    restart: always
    container_name: scan
    depends_on:
      - db
    volumes:
      - ./config1.json:/config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_URI: mongodb://host.docker.internal/blockDB
    command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 30 -- npm run start"

  # faucet:
  #   image: "nara7875/acentfaucet:2"
  #   ports:
  #     - 3014:3001
  #   restart: always
  #   container_name: faucet
  #   volumes:
  #     - ./config.json:/config.json
  #     - ./.env:/.env
  #   command : bash -c "/wait-for-it.sh -h mongo -p 27017 -t 30 -- npm run start"
  
  db:
    image: "mongo"
    depends_on:
      - posa1
      - posa2
      - posa3
      - posa4
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "[blockDB]"
    container_name: db